<?
$PERM["profile-buyer"]["6"]="X";
$PERM["profile-buyer"]["7"]="D";
$PERM["profile-buyer"]["*"]="D";
$PERM["ads"]["8"]="X";
$PERM["profile_seller"]["*"]="D";
$PERM["profile_seller"]["7"]="X";
$PERM["search"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>